[build]
  command = "npm run build"
  publish = "dist"
  
  # Esta es la instrucción clave que soluciona el error.
  # Le dice a Netlify que ignore esta clave específica durante el escaneo de secretos.
  [build.environment]
    SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY"

[functions]
  directory = "netlify/functions"

[blobs]
  store = "activation-codes"